## 应用端焦上色
server:
  port: 8010

logging:
  level:
    org.springframework.security: debug

security:
  oauth2:
    resource:
      ## 从认证授权中心上验证token
      token-info-uri: http://localhost:8090/oauth/check_token
      prefer-token-info: true
    client:
      access-token-uri: http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorization
      ## appid
      client-id: clientId_1
      # appSecret
      client-secret: 123456
